[package]
name = "myanimelist"
version = "0.1.0"
authors = ["Cam Cope <github@camcope.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
actix-web = "3.0.0-beta.1"
actix-session = "0.4.0-alpha.1"
dotenv = "0.15"
oauth2 = "4.0.0-alpha.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
url = "*"
