[package]
name = "myanimelist"
version = "0.1.0"
authors = ["Cam Cope <github@camcope.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
actix = "3"
dotenv = "0.15"
oauth2 = "4.0.0-alpha.1"
reqwest = "*"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
url = "*"
